name: tmdb_movie_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  equatable: ^2.0.3
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.7
  image_picker: ^0.8.2
  intl: ^0.17.0
  path_provider: ^2.0.2
  sembast: ^3.1.0+2
  shared_preferences: ^2.0.6
  image_cropper: ^1.4.1
  flutter_bloc: ^7.0.1
  shimmer: ^2.0.0
  permission_handler: ^8.1.3
  provider: ^6.0.2
  flutter_local_notifications: ^9.2.0
  uuid: ^3.0.5
  rxdart: ^0.27.3
  google_fonts: ^2.1.0
  android_alarm_manager_plus: ^2.0.4
  
dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.0.17
  build_runner: ^2.1.7
  test_cov_console: ^0.2.0
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf